---
title: "dataCleaning"
format: 
  html:
    embed-resources: true
editor: source
execute:
  echo: false
---

```{r setup}
# has WNBA pbp, box data
#install.packages("wehoop")
# for making a plot on a basketball court lol
#install.packages("sportyR")

library(tidyverse)
library(wehoop)
library(sportyR)
```

```{r load data}
# 3 years of data, there was a rule change since 
season_years <- c(2022:2024)

pbp_data <- load_wnba_pbp(seasons = season_years)

espn_wnba_teams()
```

```{r preview data}
head(pbp_data)
unique(pbp_data$type_text)
```

```{r filter shot data}
shot_data <- pbp_data |>
  filter(shooting_play == TRUE,
         str_detect(type_text, "Free Throw") == FALSE,
         season_type == 2,
         # remove for-fun teams: Team Stewart, Team Wilson, Team USA, etc
         !team_id %in% c(112530, 126287, 97, 96))

head(shot_data)

shot_data |>
  slice_min(coordinate_y_raw)
```

```{r box data -- player info, seasonal stats}
box_data <- load_wnba_player_box(seasons = c(2022:2024)) |>
  filter(season_type == 2,
         !team_id %in% c(126287, 112530, 97, 96))

head(box_data)
```

```{r summary by season, player}
# summarize by game, player

# replace NAs with 0s for summary (how do I use across(~.) again?)
sum_stats <- box_data |>
  mutate(minutes = case_when(is.na(minutes) ~ 0,
            !is.na(minutes) ~ minutes),
         points = case_when(is.na(points) ~ 0,
            !is.na(points) ~ points),
         field_goals_attempted = case_when(is.na(field_goals_attempted) ~ 0,
                            !is.na(field_goals_attempted) ~ field_goals_attempted)) |>
  
  group_by(athlete_display_name) |>
  
  summarize(total_minutes = sum(minutes),
    avg_minutes_played = round(mean(minutes),2), 
    total_fg_att = sum(field_goals_attempted),
    fg_att_min = sum(field_goals_attempted)/sum(minutes),
            ppm = round(mean(sum(points)/sum(minutes)), 2))

# this line assumes no change of position in the included years 
# (takes first position for each athlete)
sum_stats_pos <- sum_stats |>
  left_join(box_data[, c(7, 38)], multiple = "first")

sum_stats |>
  ggplot(aes(x = avg_minutes_played)) +
  geom_density()

sum_stats |>
  ggplot(aes(x = fg_att_min)) +
  geom_density()

sum_stats_pos |> ggplot(aes(x = avg_minutes_played, color = athlete_position_abbreviation)) +
  geom_density()

length(unique(shot_data$athlete_id_1))
```

235 unique athletes took shots in these 3 seasons.

```{r summary across all players, by season}
box_data |>
  mutate(minutes = case_when(is.na(minutes) ~ 0,
            !is.na(minutes) ~ minutes),
         points = case_when(is.na(points) ~ 0,
            !is.na(points) ~ points),
         field_goals_attempted = case_when(is.na(field_goals_attempted) ~ 0,
                            !is.na(field_goals_attempted) ~ field_goals_attempted)) |>
  group_by(season) |>
  summarize(avg_points = mean(points),
            avg_playtime = mean(minutes),
            avg_ppm = mean(sum(points)/sum(minutes)),
            sd_points = sd(points),
            sd_playtime = sd(minutes),
            avg_fg_att = mean(field_goals_attempted),
            sd_fg_att = sd(field_goals_attempted))
```

```{r example shot data plot}

geom_basketball(league = "WNBA", 
                    display_range = "offense",
                    color_updates = list(
                      offensive_half_court = "white",
                      defensive_half_court = "white",
                      court_apron = "white",
                      center_circle_fill = "white",
                      two_point_range = "white",
                      painted_area = "white",
                      free_throw_circle_fill = "white",
                      basket_ring = "black")) +
  geom_point(data = shot_data, aes(x = abs(coordinate_x)+4, y = coordinate_y, color = scoring_play))

# heat map kinda thing for percent shooting by zone etc
# this is helpful for individual players


shot_data |>
  mutate(shot_distance = sqrt(coordinate_x^2 + coordinate_y^2)) |>
  ggplot(aes(x = shot_distance)) + 
  geom_density()


```

```{r look at streaks}

streak_data <- shot_data |>
  group_by(game_id, athlete_id_1) |>
  mutate(is_make  = scoring_play == TRUE,
    is_miss  = !is_make,
    miss_grp = cumsum(is_miss),               
    make_grp = cumsum(is_make)) |>
  group_by(game_id, athlete_id_1, miss_grp) |>
  mutate(make_streak_length = if_else(is_make, cumsum(is_make), 0)) |>
  group_by(game_id, athlete_id_1, make_grp) |>
  mutate(miss_streak_length = if_else(is_miss, cumsum(is_miss), 0),
         shot_distance = sqrt(coordinate_x^2 + coordinate_y^2)) |>
  ungroup()

streak_data |>
  slice_max(make_streak_length)

streak_data |>
  slice_max(miss_streak_length)

```

```{r streak length distributions}

streak_data |>
  ggplot(aes(x = make_streak_length)) +
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = seq(0, 10))


streak_data |>
  ggplot(aes(x = miss_streak_length)) +
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = seq(0, 15))

streak_data |>
  slice_max(make_streak_length)

streak_data |>
  slice_max(miss_streak_length)

streak_data |>
  filter(make_streak_length > 3)

# use overall shot distance (x_coord_raw-25)^2 + y_coord_raw^2

# use time variable more

streak_data |>
  ggplot(aes(x = make_streak_length, y = shot_distance)) + geom_point() + geom_smooth(method = "lm")

```

```{r MVP 2022 aja wilson}

# box_data |>
#   filter(athlete_display_name == "A'ja Wilson")
# Aja wilson athlete id = 3149391
shot_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391,
         scoring_play == TRUE) |>
  ggplot(aes(x = coordinate_x_raw, y = coordinate_y_raw)) +
  geom_point()

shot_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = coordinate_x_raw, color = scoring_play)) +
  geom_density()

shot_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = coordinate_y_raw, color = scoring_play)) +
  geom_density() +
  coord_flip()

shot_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391,
         scoring_play) |>
  group_by(game_id) |>
  summarize()


streak_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = make_streak_length)) +
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = seq(0, 10))
  

```

```{r MVP 2023 breanna stewart}

# box_data |>
# filter(athlete_display_name == "Breanna Stewart")
# Breanna Stewart athlete id = 2998928

shot_data |>
  filter(season == 2023,
         athlete_id_1 == 2998928,
         scoring_play == TRUE) |>
  ggplot(aes(x = coordinate_x_raw, y = coordinate_y_raw)) +
  geom_point()

shot_data |>
  filter(season == 2023,
         athlete_id_1 == 2998928) |>
  ggplot(aes(x = coordinate_x_raw, color = scoring_play)) +
  geom_density()

shot_data |>
  filter(season == 2023,
         athlete_id_1 == 2998928) |>
  ggplot(aes(x = coordinate_y_raw, color = scoring_play)) +
  geom_density() +
  coord_flip()

shot_data |>
  filter(season == 2023,
         athlete_id_1 == 2998928,
         scoring_play) |>
  group_by(game_id) |>
  summarize()

streak_data |>
  filter(season == 2023,
         athlete_id_1 == 2998928) |>
  ggplot(aes(x = make_streak_length)) +
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = seq(0, 10))
```

```{r}
shot_data |>
  filter(season == 2024,
         athlete_id_1 == 3149391,
         scoring_play == TRUE) |>
  ggplot(aes(x = coordinate_x_raw, y = coordinate_y_raw)) +
  geom_point()

shot_data |>
  filter(season == 2024,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = coordinate_x_raw, color = scoring_play)) +
  geom_density()

shot_data |>
  filter(season == 2022,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = coordinate_y_raw, color = scoring_play)) +
  geom_density() +
  coord_flip()

shot_data |>
  filter(season == 2024,
         athlete_id_1 == 3149391,
         scoring_play) |>
  group_by(game_id) |>
  summarize()

streak_data |>
  filter(season == 2024,
         athlete_id_1 == 3149391) |>
  ggplot(aes(x = make_streak_length)) +
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = seq(0, 10))
  
```


## Team-wide data

```{r}
# getting a sense of what Dr. Ross' code does

streak_length <- 3

test_streak <- streak_data |>
  filter(game_id == 401391860,
         team_id == 8)

rle(test_streak$is_make)

run_lengths = rle(test_streak$is_make)
```

```{r}

# load in Dr. Ross' streak statistics code

streak_stats = function(results_sequence, streak_length){
  n_trials = length(results_sequence)
  n_success = sum(results_sequence)
  
  run_lengths = rle(results_sequence)$lengths
  if_run_success = rle(results_sequence)$values
  n_runs = length(run_lengths)
  
  # runs of successes
  longest_run_success = max(run_lengths*if_run_success)
  n_runs_success = sum(if_run_success)
  
  # successes after streaks of Successes
  run_lengths_adj = run_lengths - streak_length + 1
  run_values_adj_S =
    if_run_success *
    (!((if_run_success == 1) &
         (run_lengths < streak_length)))
  n_after_Sstreak = sum(run_lengths_adj * run_values_adj_S) -
    run_values_adj_S[length(run_values_adj_S)]
  n_success_after_Sstreak = sum((run_lengths - streak_length) * run_values_adj_S)
  
  # runs of failures
  longest_run_failure = max(run_lengths*(1-if_run_success))
  n_runs_failure = sum(1-if_run_success)
  
  # successes after streaks of Failures
  run_values_adj_F =
    (1-if_run_success) *
    (!((if_run_success == 0) &
         (run_lengths < streak_length)))
  n_after_Fstreak = sum(run_lengths_adj * run_values_adj_F) -
    run_values_adj_F[length(run_values_adj_F)]
  n_success_after_Fstreak = n_after_Fstreak -
    sum((run_lengths - streak_length) * run_values_adj_F)
  
  # Proportion of hits on trials after streaks
  phat_after_Sstreak = n_success_after_Sstreak / n_after_Sstreak
  
  # Difference in proportion of hits (trials after streaks - all other trials)
  phat_after_no_Sstreak = (n_success - n_success_after_Sstreak)/
    (n_trials - n_after_Sstreak)
  phat_Sstreak_vs_others = phat_after_Sstreak - phat_after_no_Sstreak
  
  # Difference in proportion of hits (trials after hit streaks - trials after miss streaks)
  phat_after_Fstreak = n_success_after_Fstreak / n_after_Fstreak
  phat_Sstreak_vs_Fstreak = phat_after_Sstreak - phat_after_Fstreak
  
  # Hit streak frequency - proportion of trials that occur after hit streaks
  Sstreak_frequency  = n_after_Sstreak / (n_trials - streak_length)
  
  # collect the streak stats for the results sequence
  return(data.frame(phat_after_Sstreak,
                    phat_Sstreak_vs_others,
                    phat_Sstreak_vs_Fstreak,
                    Sstreak_frequency,
                    longest_run_success,
                    n_runs
                    #                     n_runs_success,
                    #                     phat_after_Fstreak,
                    #                     n_runs_failure,
                    #                     longest_run_failure,
  ))
}


streak_stats(test_streak$is_make, streak_length)
```

```{r}
# visualize streak statistics, try to investigate outliers
# need help labeling which streak is which according to the paper

streak_length <- 3
team_streaks <- streak_data |>
  group_by(game_id, team_id, season) |>
  summarize(streak_stats = list(streak_stats(is_make, streak_length)), .groups = "drop") |>
  unnest(streak_stats) |>
  mutate(team_id = as.factor(team_id))

team_streaks |>
  ggplot(aes(x = phat_after_Sstreak)) +
  geom_histogram()

team_streaks |>
  ggplot(aes(x = phat_Sstreak_vs_others)) +
  geom_histogram()

team_streaks |>
  ggplot(aes(x = phat_Sstreak_vs_Fstreak)) +
  geom_histogram()

team_streaks |>
  ggplot(aes(x = Sstreak_frequency)) +
  geom_histogram()

team_streaks |>
  ggplot(aes(x = longest_run_success)) +
  geom_histogram()

team_streaks |>
  ggplot(aes(x = n_runs)) +
  geom_histogram()

team_streaks |>
  slice_max(phat_after_Sstreak)

team_streaks |>
  slice_max(longest_run_success)

streak_data |>
  filter(game_id == 401620372,
         team_id == 8)

streak_data |>
  filter(game_id == 401391743,
         team_id == 18)

# shot distance vs make streak length for longest streak in dataset
streak_data |>
  filter(game_id == 401620372,
         team_id == 8) |>
  ggplot(aes(x = make_streak_length, y = shot_distance)) + geom_point() + geom_smooth(method = "lm")

streak_data |>
  filter(game_id == 401391743,
         team_id == 18) |>
  ggplot(aes(x = make_streak_length, y = shot_distance)) + geom_point() + geom_smooth(method = "lm")
```

Investigating the champions for each year: how do their distributions look compared to the league average?

```{r}
# las vegas aces, 2022

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = phat_after_Sstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = phat_Sstreak_vs_others)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = phat_Sstreak_vs_Fstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = Sstreak_frequency)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = longest_run_success)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2022) |>
  ggplot(aes(x = n_runs)) + geom_histogram()
```

```{r}
# las vegas aces, 2023

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = phat_after_Sstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = phat_Sstreak_vs_others)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = phat_Sstreak_vs_Fstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = Sstreak_frequency)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = longest_run_success)) + geom_histogram()

team_streaks |>
  filter(team_id == 17,
         season == 2023) |>
  ggplot(aes(x = n_runs)) + geom_histogram()
```


```{r}
# new york liberty, 2024

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = phat_after_Sstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = phat_Sstreak_vs_others)) + geom_histogram()

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = phat_Sstreak_vs_Fstreak)) + geom_histogram()

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = Sstreak_frequency)) + geom_histogram()

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = longest_run_success)) + geom_histogram()

team_streaks |>
  filter(team_id == 9,
         season == 2024) |>
  ggplot(aes(x = n_runs)) + geom_histogram()
```
