---
title: "PoissonProcess"
format: html
---

```{r setup}
library(mgcv)
library(depmixS4)
library(tidyverse)
df_shots <- read.csv("df_shots.csv") |>
  dplyr::select(-X)
# individual shot data
head(df_shots)
shots_discrete <- read.csv("shots_discrete.csv") |>
  dplyr::select(-X)
```


```{r}
# select game, team, time elapsed, score value of a shot
game_time_score <- df_shots |>
  filter(team_id != 17, season == 2022) |>
  select(game_id, team_id, time_elapsed, score_value)

# make discrete times:
# group observations by game and team
# for each game and team, find the time of the last observation
# turn data into one observation for each second between 0 and last time observed
discrete_times <- game_time_score |>
  select(game_id, time_elapsed, team_id) |>
  group_by(game_id, team_id) |>
  summarize(max_time = max(time_elapsed)) |>
  rowwise() |>
  mutate(time_elapsed = list(0:max_time)) |>
  unnest(time_elapsed)

# drop max_time variable
# join discrete times onto shot data by game and team, and time elapsed
# if there is no shot at that time, event 1
# if there is a 2-pt attempt, event 2
# if there is a 3-pt attempt, event 3
df_discrete <- discrete_times |>
  select(!max_time) |>
  left_join(game_time_score,
            by = join_by(game_id, team_id, time_elapsed)) |>
  mutate(event = case_when(score_value == 0 ~ 2,
                           score_value %in% c(2, 3) ~ 3)) |>
  # sanity check: do values in events and score_value match up?
   replace_na(list(event = 1)) |>
  # sanity check: do values in events and score_value match up?
   select(!score_value)
```


```{r}
# bin by every 2 mins:
bin_width <- 120


binned_shot_data <- df_discrete |>
  mutate(bin = ceiling(time_elapsed/bin_width),
         attempt_2 = (event == 2),
         attempt_3 = (event == 3)) |>
  filter(bin > 0) |>
  group_by(bin) |>
  summarize(y = sum(attempt_2)) 
binned_shot_data$bin_width <- bin_width
binned_shot_data$centroid <- (binned_shot_data$bin*120 + (binned_shot_data$bin - 1)*120)/2

fit_sp_gam <- gam(y ~ s(centroid, bs = "tp", k = 19) +  + offset(log(bin_width)),
                  family = poisson(),
                  method = "REML",
                  data = binned_shot_data)
summary(fit_sp_gam)
plot(fit_sp_gam)
```

```{r}
# create dataset of poisson distributed points scored
poisson_shots <- df_shots |>
  mutate(
  athlete_id_1 = as.factor(athlete_id_1),
  game_id = as.factor(game_id)
  ) |>
  # filter down to only a single team's games
  filter(team_id == 17,
         qtr < 5,
         !is.na(athlete_id_1),
         season == 2022) |>
  group_by(game_id) |>
  # create an iterative score variable that updates with each shot
  mutate(team_score = cumsum(score_value)) |>
  ungroup() |>
  dplyr::select(athlete_id_1, score_value, shot_dist, season, game_id, time_elapsed, team_score)

# create table where each entry is number of shots in a game
game_obslength <- poisson_shots |>
  group_by(game_id) |>
  # count number of shots by game
  summarize(n = n())

# create vector of game shot attempts from previous table
game_obslength_vec <- game_obslength[,2] |>
  as.vector()

# create new table where event value is given by score outcome for multinomial model use
multinomial_shots <- df_shots |>
  mutate(event_value = as.factor(case_when(
    # (3 point make = 4, 3 point miss = 3, 2 point make = 2, 2 point miss = 1)
    str_detect(text, "three point") & scoring_play ~ 4,
    str_detect(text, "three point") & !scoring_play ~ 3,
    !str_detect(text, "three point") & scoring_play ~ 2,
    !str_detect(text, "three point") & !scoring_play ~ 1
  )),
  athlete_id_1 = as.factor(athlete_id_1),
  game_id = as.factor(game_id)) |>
  filter(team_id == 17,
         qtr < 5,
         !is.na(athlete_id_1),
         season == 2022) |>
  group_by(game_id) |>
  mutate(team_score = cumsum(score_value)) |>
  ungroup() |>
  dplyr::select(athlete_id_1, shot_dist, event_value, season, game_id, time_elapsed)

# create new table where event value is given by success/fail for binomial model use
binomial_shots <- df_shots |>
  mutate(shot_made = if_else(
    # 1 = make, 0 = miss
   score_value == 0,
   0,
   1
  ),
  athlete_id_1 = as.factor(athlete_id_1),
  game_id = as.factor(game_id)) |>
  filter(team_id == 17,
         qtr < 5,
         !is.na(athlete_id_1),
         season == 2022) |>
  group_by(game_id) |>
  mutate(team_score = cumsum(score_value)) |>
  ungroup()
```

```{r}
#| warning: false
# fit hmm with poisson family component
mod <- depmix(team_score~shot_dist, nstates = 2, family=poisson(), ntimes = game_obslength_vec[[1]], data = poisson_shots)
fitted.mod <- fit(mod)
# see posterior parameter estimates
summary(fitted.mod)
logLik(fitted.mod)
# see numerically optimized state sequence
posterior(fitted.mod)$state
# NOT USEFUL AT ALL WTF
plot(posterior(fitted.mod)$state, type = "l",
     ylab = "Hidden State",
     xlab = "Time",
     main = "Estimated Hidden States Over Time")
# see state probability at each observation -- Poisson model seems to do the worst
forwardbackward(fitted.mod)$gamma
```

```{r}
mod2 <- depmix(event_value ~ shot_dist, nstates = 2, family=multinomial(), ntimes = game_obslength_vec[[1]], data = multinomial_shots)
fitted.mod2 <- fit(mod2)
summary(fitted.mod2)
logLik(fitted.mod2)
forwardbackward(fitted.mod2)$gamma
posterior(fitted.mod2)$state

mod2.5 <- depmix(event_value ~ shot_dist, nstates = 3, family=multinomial(), ntimes = game_obslength_vec[[1]], data = multinomial_shots)
fitted.mod2.5 <- fit(mod2.5)
summary(fitted.mod2.5)
logLik(fitted.mod2.5)
forwardbackward(fitted.mod2.5)$gamma
posterior(fitted.mod2.5)$state
```

```{r}
#| warning: false
# the best model so far:
mod3 <- depmix(shot_made ~ shot_dist + athlete_id_1, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.mod3 <- fit(mod3)
summary(fitted.mod3)
logLik(fitted.mod3)
forwardbackward(fitted.mod3)$gamma
posterior(fitted.mod3)$state
plot(posterior(fitted.mod3)$state, type = "l",
     ylab = "Hidden State",
     xlab = "Time",
     main = "Estimated Hidden States Over Time")






mod3.5 <- depmix(shot_made ~ shot_dist + athlete_id_1, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.mod3.5 <- fit(mod3.5)
summary(fitted.mod3.5)
logLik(fitted.mod3.5)
AIC(fitted.mod3.5)
forwardbackward(fitted.mod3.5)$gamma
posterior(fitted.mod3.5)$state

mod4 <- depmix(shot_made ~ shot_dist, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.mod4 <- fit(mod4)
summary(fitted.mod4)
logLik(fitted.mod4)
forwardbackward(fitted.mod4)$gamma
posterior(fitted.mod4)$state
AIC(fitted.mod4)

mod5 <- depmix(shot_made ~ shot_dist + time_elapsed, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.mod5 <- fit(mod5)
summary(fitted.mod5)
logLik(fitted.mod5)
AIC(fitted.mod5)

binmodfull <- depmix(shot_made ~ shot_dist + time_elapsed + athlete_id_1, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.modfull <- fit(binmodfull)
summary(fitted.modfull)
logLik(fitted.modfull)
AIC(fitted.modfull)

nullmod <- depmix(shot_made ~ 1, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.nullmod <- fit(nullmod)
summary(fitted.nullmod)
logLik(fitted.nullmod)

binmod2states <- depmix(shot_made ~ shot_dist + time_elapsed + athlete_id_1, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
fitted.binmod2states <- fit(binmod2states)
summary(fitted.binmod2states)
logLik(fitted.binmod2states)
AIC(fitted.binmod2states)
```

```{r}
#| warning: false


fits <- lapply(1:10, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist + time_elapsed + athlete_id_1, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE))
})

best_fit <- fits[[which.max(sapply(fits, logLik))]]

fits <- lapply(1:10, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist + athlete_id_1, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE))
})

best_fit2 <- fits[[which.max(sapply(fits, logLik))]]

fits <- lapply(1:10, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist + time_elapsed, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE))
})

best_fit3 <- fits[[which.max(sapply(fits, logLik))]]
posterior(best_fit3)$state

fits <- lapply(1:10, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist + athlete_id_1 + time_elapsed, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE, maxit = 2000, tol = 1e-8))
})

best_fit4 <- fits[[which.max(sapply(fits, logLik))]]
forwardbackward(best_fit4)$gamma
posterior(best_fit4)$state
plot(posterior(best_fit4)$state)
summary(best_fit4)

fits <- lapply(1:10, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist + athlete_id_1, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE, maxit = 2000, tol = 1e-8))
})

best_fit5 <- fits[[which.max(sapply(fits, logLik))]]

fits <- lapply(1:50, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist, nstates = 3, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE, maxit = 2000, tol = 1e-8))
})

best_fit6 <- fits[[which.max(sapply(fits, logLik))]]

fits <- lapply(1:50, function(i) {
  set.seed(i)
  mod <- depmix(shot_made ~ shot_dist, nstates = 2, family=binomial(), ntimes = game_obslength_vec[[1]], data = binomial_shots)
  fit(mod, emcontrol = em.control(random.start = TRUE, maxit = 2000, tol = 1e-8))
})

best_fit7 <- fits[[which.max(sapply(fits, logLik))]]
summary(best_fit7)
posterior(best_fit7)$state
actual.vs.pred <- cbind(binomial_shots, as.tibble(posterior(best_fit7)$state))


llratio(best_fit4, best_fit5)
llratio(best_fit, best_fit2)
llratio(best_fit3, best_fit7)

```

