---
title: "Streak Stats"
author: "Ruben Jimenez"
format: html
editor: source
embed-resources: true
---

```{r setup}
#| include: false

library(sportyR)
library(tidyverse)
library(lme4) 
library(splines)
library(viridis)
library(glue)
library(janitor)
library(broom.mixed)

df_shots <- read_csv("df_shots.csv") |>
  dplyr::select(-`...1`) |>
  mutate(shot_type = if_else(str_detect(text, "three point") | shot_dist > 25, 3, 2),
         scoring_play = as.integer(scoring_play))
head(df_shots) 

df_shots |>
  filter((team_id == 17 & season == 2022) | (team_id == 17 & season == 2023) | (team_id == 9 & season == 2024)) |>
  summarize(n_games = n_distinct(game_id),
            n_shots = n())
```

```{r}
# function that returns basic streak statistics given a sequence
streak_stats = function(results_sequence, streak_length){
  n_trials = length(results_sequence)
  n_success = sum(results_sequence)
  
  run_lengths = rle(results_sequence)$lengths
  if_run_success = rle(results_sequence)$values
  n_runs = length(run_lengths)
  
  # runs of successes
  longest_run_success = max(run_lengths*if_run_success)
  n_runs_success = sum(if_run_success)
  
  # successes after streaks of Successes
  run_lengths_adj = run_lengths - streak_length + 1
  run_values_adj_S =
    if_run_success *
    (!((if_run_success == 1) &
         (run_lengths < streak_length)))
  n_after_Sstreak = sum(run_lengths_adj * run_values_adj_S) -
    run_values_adj_S[length(run_values_adj_S)]
  n_success_after_Sstreak = sum((run_lengths - streak_length) * run_values_adj_S)
  
  # runs of failures
  longest_run_failure = max(run_lengths*(1-if_run_success))
  n_runs_failure = sum(1-if_run_success)
  
  # successes after streaks of Failures
  run_values_adj_F =
    (1-if_run_success) *
    (!((if_run_success == 0) &
         (run_lengths < streak_length)))
  n_after_Fstreak = sum(run_lengths_adj * run_values_adj_F) -
    run_values_adj_F[length(run_values_adj_F)]
  n_success_after_Fstreak = n_after_Fstreak -
    sum((run_lengths - streak_length) * run_values_adj_F)
  
  # Proportion of hits on trials after streaks
  phat_after_Sstreak = n_success_after_Sstreak / n_after_Sstreak
  
  # Difference in proportion of hits (trials after streaks - all other trials)
  phat_after_no_Sstreak = (n_success - n_success_after_Sstreak)/
    (n_trials - n_after_Sstreak)
  phat_Sstreak_vs_others = phat_after_Sstreak - phat_after_no_Sstreak
  
  # Difference in proportion of hits (trials after hit streaks - trials after miss streaks)
  phat_after_Fstreak = n_success_after_Fstreak / n_after_Fstreak
  phat_Sstreak_vs_Fstreak = phat_after_Sstreak - phat_after_Fstreak
  
  # Hit streak frequency - proportion of trials that occur after hit streaks
  Sstreak_frequency  = n_after_Sstreak / (n_trials - streak_length)
  
  # collect the streak stats for the results sequence
  return(data.frame(phat_after_Sstreak,
                    phat_Sstreak_vs_others,
                    phat_Sstreak_vs_Fstreak,
                    Sstreak_frequency,
                    longest_run_success,
                    n_runs
                    #                     n_runs_success,
                    #                     phat_after_Fstreak,
                    #                     n_runs_failure,
                    #                     longest_run_failure,
  ))
}

# For only Sstreak - others
phat_Sstreak_vs_others <- function(results_sequence, streak_length){
  n_trials = length(results_sequence)
  n_success = sum(results_sequence)
  
  run_lengths = rle(results_sequence)$lengths
  if_run_success = rle(results_sequence)$values
  
  # successes after streaks of Successes
  run_lengths_adj = run_lengths - streak_length + 1
  run_values_adj_S =
    if_run_success *
    (!((if_run_success == 1) &
         (run_lengths < streak_length)))
  n_after_Sstreak = sum(run_lengths_adj * run_values_adj_S) -
    run_values_adj_S[length(run_values_adj_S)]
  n_success_after_Sstreak = sum((run_lengths - streak_length) * run_values_adj_S)
  
  if (n_after_Sstreak <= 0) return(NA_real_)
  if ((n_trials - n_after_Sstreak) <= 0) return(NA_real_)
  
  phat_after_Sstreak = n_success_after_Sstreak / n_after_Sstreak
  phat_after_Sstreak
  
  phat_after_no_Sstreak = (n_success - n_success_after_Sstreak)/
    (n_trials - n_after_Sstreak)
  
  phat_after_Sstreak - phat_after_no_Sstreak
}

# For only Sstreak - Fstreak
phat_Sstreak_Fstreak <- function(results_sequence, streak_length){
  n_trials = length(results_sequence)
  n_success = sum(results_sequence)
  
  run_lengths = rle(results_sequence)$lengths
  if_run_success = rle(results_sequence)$values
  
  # successes after streaks of Successes
  run_lengths_adj = run_lengths - streak_length + 1
  run_values_adj_S =
    if_run_success *
    (!((if_run_success == 1) &
         (run_lengths < streak_length)))
  n_after_Sstreak = sum(run_lengths_adj * run_values_adj_S) -
    run_values_adj_S[length(run_values_adj_S)]
  n_success_after_Sstreak = sum((run_lengths - streak_length) * run_values_adj_S)
  
  # successes after streaks of Failures
  run_values_adj_F =
    (1-if_run_success) *
    (!((if_run_success == 0) &
         (run_lengths < streak_length)))
  n_after_Fstreak = sum(run_lengths_adj * run_values_adj_F) -
    run_values_adj_F[length(run_values_adj_F)]
  n_success_after_Fstreak = n_after_Fstreak -
    sum((run_lengths - streak_length) * run_values_adj_F)
  
  phat_after_Sstreak = n_success_after_Sstreak / n_after_Sstreak
  phat_after_Fstreak = n_success_after_Fstreak / n_after_Fstreak
  phat_Sstreak_vs_Fstreak = phat_after_Sstreak - phat_after_Fstreak
  
  phat_Sstreak_vs_Fstreak
  
}

# For only Sstreak
phat_Sstreak <- function(results_sequence, streak_length){
  
  n_trials = length(results_sequence)
  n_success = sum(results_sequence)
  
  run_lengths = rle(results_sequence)$lengths
  if_run_success = rle(results_sequence)$values
  
  # successes after streaks of Successes
  run_lengths_adj = run_lengths - streak_length + 1
  run_values_adj_S =
    if_run_success *
    (!((if_run_success == 1) &
         (run_lengths < streak_length)))
  n_after_Sstreak = sum(run_lengths_adj * run_values_adj_S) -
    run_values_adj_S[length(run_values_adj_S)]
  n_success_after_Sstreak = sum((run_lengths - streak_length) * run_values_adj_S)
  
  phat_after_Sstreak = n_success_after_Sstreak / n_after_Sstreak
  phat_after_Sstreak
}
```



```{r}
set.seed(619)

# grab one season data
pull_list_games <- function(shots_df, TEAMID, SEASON){
  shots_df |>
    arrange(team_id, game_id, time_elapsed) |>
    filter(team_id == TEAMID,
         season == SEASON) |>
  mutate(shot_made = as.integer(scoring_play)) |>
  select(game_id, time_elapsed, shot_made) |>
    group_by(game_id) |>
    group_split()
}

# grab lv 2022, lv 2023, ny 2024 (champs each season)
lv_2022_games <- pull_list_games(df_shots, 17, 2022)
lv_2023_games <- pull_list_games(df_shots, 17, 2023)
ny_2024_games <- pull_list_games(df_shots, 9, 2024)

# number of permutations to run for each game
n_trials <- 10000

# iterate over all games in the list
# take a random permutation of the shots in game, compute statistic
perm_stats_2022 <- lv_2022_games |> map(~replicate(
    n_trials,
    phat_Sstreak_Fstreak(sample(.x$shot_made), 3)
  )
)

# plot all the games
map(perm_stats_2022, hist)
results_2022 <- tibble(
  game_id = map_int(lv_2022_games, ~ .x$game_id[1]),
  observed = map_dbl(lv_2022_games, ~ phat_Sstreak_Fstreak(.x$shot_made, 3)),
  perm_dist = perm_stats_2022,
  mean = map_dbl(perm_stats_2022, \(x) mean(x, na.rm = T)),
  sd = map_dbl(perm_stats_2022, \(x) sd(x, na.rm = T))
) |>
  mutate(
    p_value = map2_dbl(observed, perm_dist, ~ mean(.y >= .x, na.rm = T))
  )

results_2022 |>
  pull(p_value) |>
  hist()

results_2022 |>
  arrange(p_value) |>
  mutate(p_adj = p.adjust(p_value, "BY")) |>
  select(game_id, observed, p_value, p_adj, mean, sd) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2022) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2022_permutations.csv")



df_shots |> filter((team_id == 17 & season %in% c(2022, 2023)) | (team_id == 9 & season == 2024)) |> group_by(season, team_id, game_id) |>
    arrange(season, team_id) |>
    summarize(streak_stat = streak_stats(scoring_play, 3)) |>
  unnest_wider(streak_stat)

# game_id == 401391727

results_2022 |> 
  unnest_longer(perm_dist) |>
  filter(game_id == 401391727) |>
  ggplot(aes(x = perm_dist)) + geom_histogram(aes(fill = after_stat(x >= 0.5)), bins = 40) + scale_fill_manual(
    values = c("FALSE" = "gray40", "TRUE" = "red"),
    guide = "none"   # removes legend
  ) + geom_vline(
    aes(xintercept = observed),
    color = "red"
  ) + geom_vline(aes(xintercept = mean), color = "blue", lty = 2) +
  labs(title = "Streak Statistic for 2022 LV Aces vs. LA Sparks on 6/11/22",
  subtitle = "Over permuted distribution",
   x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
  y = "Frequency") + theme_minimal() + theme(panel.grid.minor = element_blank()) + annotate("text", x = .72, y = 1000, label = "P-Value = 0.004") + annotate("text", label = "Sample Mean = -0.12", x = .17, y = 1000)


```

```{r}
set.seed(619)
perm_stats_2023 <- lv_2023_games |> map(~replicate(
    n_trials,
    phat_Sstreak_Fstreak(sample(.x$shot_made), 3)
  )
)

# plot all the games
map(perm_stats_2023, hist)
results_2023 <- tibble(
  game_id = map_int(lv_2023_games, ~ .x$game_id[1]),
  observed = map_dbl(lv_2023_games, ~ phat_Sstreak_Fstreak(.x$shot_made, 3)),
  perm_dist = perm_stats_2023,
  mean = map_dbl(perm_stats_2023, \(x) mean(x, na.rm = T)),
  sd = map_dbl(perm_stats_2023, \(x) sd(x, na.rm = T))
) |>
  mutate(
    p_value = map2_dbl(observed, perm_dist, ~ mean(.y >= .x, na.rm = T))
  )

results_2023 |>
  pull(p_value) |>
  hist()

results_2023 |>
  na.omit(p_value) |>
  arrange(p_value) |>
  mutate(p_adj = p.adjust(p_value, "BY")) |>
  select(game_id, observed, p_value, p_adj, mean, sd) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2023) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2023_permutations.csv")

results_2023 |>
  na.omit(p_value) |>
  arrange(p_value) |>
  mutate(p_adj = p.adjust(p_value, "BY")) |>
  pull(observed) |>
  t.test(mu = 0)

results_2023 |>
  mutate(
    perm_mean = map_dbl(perm_dist, ~ mean(.x, na.rm = TRUE)),
    bias_adj = observed - perm_mean
  ) |>
  select(game_id, p_value, bias_adj)
```

```{r}
set.seed(619)
perm_stats_2024 <- ny_2024_games |> map(~replicate(
    n_trials,
    phat_Sstreak_Fstreak(sample(.x$shot_made), 3)
  )
)

# plot all the games
map(perm_stats_2024, hist)
results_2024 <- tibble(
  game_id = map_int(ny_2024_games, ~ .x$game_id[1]),
  observed = map_dbl(ny_2024_games, ~ phat_Sstreak_Fstreak(.x$shot_made, 3)),
  perm_dist = perm_stats_2024,
  mean = map_dbl(perm_stats_2024, \(x) mean(x, na.rm = T)),
  sd = map_dbl(perm_stats_2024, \(x) sd(x, na.rm = T))
) |>
  mutate(
    p_value = map2_dbl(observed, perm_dist, ~ mean(.y >= .x, na.rm = T))
  )

results_2024 |>
  pull(p_value) |>
  hist()

results_2024 |>
  na.omit(p_value) |>
  mutate(p_adj = p.adjust(p_value, "BY")) |>
  arrange(p_value) |>
  select(game_id, observed, p_value, p_adj, mean, sd) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 9, season == 2024) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2024_permutations.csv")


results_2024 |>
  mutate(
    perm_mean = map_dbl(perm_dist, ~ mean(.x, na.rm = TRUE)),
    bias_adj = observed - perm_mean
  ) |>
  select(game_id, p_value, bias_adj)
```


```{r, warning = F}
# fit GLM

glm_shots <- df_shots |>
  arrange(team_id, game_id, time_elapsed) |>
  group_by(team_id, game_id) |>
  mutate(
    miss_group = cumsum(lag(scoring_play, default = 0) == 0),  # resets after a miss
    streak = ave(scoring_play, miss_group, FUN = cumsum),      # running makes within streak
    after_3_makes = ifelse(lag(streak, default = 0) >= 3, 1, 0),
    
    make_group = cumsum(lag(scoring_play, default = 0) == 1),
    miss_streak = ave(1 - scoring_play, make_group, FUN = cumsum),
    after_3_misses = ifelse(lag(miss_streak, default = 0) >= 3, 1, 0),
    
    sequence_type = case_when(after_3_misses == 1 ~ 0,
                              after_3_makes == 1 ~ 1,
                              after_3_makes == 0 & after_3_misses == 0 ~ 2),
    streak_group = if_else(streak >= 3, "3+", "0-2"),
    streak_group = factor(streak_group, levels = c("0-2", "3+")),
    streak_group_2 = case_when(streak == 0 ~ "0",
                               streak == 1 ~ "1",
                               streak == 2 ~ "2",
                               streak == 3 ~ "3",
                               streak >= 4 ~ "4+"),
    streak_before = streak - scoring_play,
    streak_before = case_when(streak_before == 0 ~ "0",
                               streak_before == 1 ~ "1",
                               streak_before == 2 ~ "2",
                               streak_before >= 3 ~ "3+"),
    miss_streak_before = miss_streak - (1 - scoring_play),
miss_streak_before = case_when(
  miss_streak_before == 0 ~ "0",
  miss_streak_before == 1 ~ "1",
  miss_streak_before == 2 ~ "2",
  miss_streak_before >= 3 ~ "3+"
)
  ) |>
  ungroup()

# null_model <- glm(scoring_play ~ factor(after_3_makes) + factor(shot_type) + factor(team_id) + time_elapsed, family = binomial(link = "logit"), data = glm_shots) 
# 


null_model <- glm(
    scoring_play ~ factor(shot_type) +
      time_elapsed +
      factor(team_id) + factor(season) + factor(season)*factor(team_id) + factor(team_id)*factor(shot_type) + factor(team_id)*time_elapsed,
    family = binomial(),
    data = glm_shots
  )

summary(null_model)

phat <- predict(null_model, newdata = glm_shots, type = "response")

glm_shots_predicted <- glm_shots |>
  cbind(phat) |>
  relocate(scoring_play, phat)

head(glm_shots_predicted)

glm_shots |>
  ggplot(aes(x = shot_dist, color = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak length before shot")

# rest of league
glm_shots |>
  filter(
    !(
      (team_id == 17 & season %in% c(2022, 2023)) |
      (team_id == 9  & season == 2024)
    )
  ) |>
  ggplot(aes(x = shot_dist, color = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", subtitle = "Rest of League 2022-2024", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1))

# 2022 lv aces
glm_shots |>
  filter(season == 2022 & team_id == 17) |>
  ggplot(aes(x = shot_dist, color = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", subtitle = "LV Aces 2022", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1))

# 2023 lv aces
glm_shots |>
  filter(season == 2023 & team_id == 17) |>
  ggplot(aes(x = shot_dist, color = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", subtitle = "LV Aces 2023", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1))

# 2024 ny liberty
glm_shots |>
  filter(season == 2024 & team_id == 9) |>
  ggplot(aes(x = shot_dist, color = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", subtitle = "NY Liberty 2024", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1))

glm_shots |>
  mutate(group = case_when(
      team_id == 17 & season == 2022 ~ "2022 LV Aces",
      team_id == 17 & season == 2023 ~ "2023 LV Aces",
      team_id == 9  & season == 2024 ~ "2024 NY Liberty",
      TRUE                           ~ "Rest of League"
    )) |>
  ggplot(aes(x = shot_dist, color = streak_before, lty = streak_before)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length", lty = "") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1)) + facet_wrap(~group) + guides(lty = "none") + scale_color_discrete(palette = "Okabe-Ito")

glm_shots |>
  ggplot(aes(x = shot_dist)) + geom_density() + theme_minimal() + theme(panel.grid.minor = element_blank()) + labs(title = "Shot Density Conditional on Previous Shot Streak Length", y = "Proportion of Shots", x = "Shot Distance (ft)", color = "Streak Length", lty = "") + scale_x_continuous(limits = c(0, 60)) + scale_y_continuous(limits = c(0, .1)) + facet_wrap(~streak_before)

glm_shots |>
  mutate(streak_before = if_else(streak_before == "3+", "3+", "< 3")) |>
  group_by(season, team_id, streak_before) |>
  summarize(shot_dist = mean(shot_dist)) |>
  ungroup() |>
  pivot_wider(names_from = streak_before, values_from = shot_dist) |>
  ggplot(aes(x = `< 3`, y = `3+`)) + geom_point(aes(color = as.factor(season))) + geom_abline(intercept = 0, slope = 1) + theme_minimal() + theme(panel.grid.minor = element_blank(),
                                                                                                                                                                 legend.position = "bottom") + labs(x = "Streak length < 3", y = "Streak length 3+", title = "Average shot distance (ft)", color = "Season") + scale_color_discrete(palette = "Okabe-Ito") + scale_x_continuous(limits = c(11, 16)) + scale_y_continuous(limits = c(11, 16))

```

## Fit New Model

```{r}
set.seed(619)
df_shots_select <- df_shots |>
                       mutate(shot_dist = as.numeric(scale(shot_dist)),
                              time_elapsed = as.numeric(scale(time_elapsed)),
                              type_id = as.factor(type_id),
                              shot_type = as.factor(shot_type),
                              team_id = as.factor(team_id),
                              season = as.factor(season),
                              season_type = as.factor(season_type),
                              athlete_id_1 = as.factor(athlete_id_1)) |>
  arrange(team_id, game_id, time_elapsed) |>
  drop_na(athlete_id_1) |>
  dplyr::select(scoring_play, shot_dist, time_elapsed, type_id, shot_type, season_type, team_id, season, athlete_id_1, game_id, time_elapsed)

# m_full <- glmer(scoring_play ~ shot_dist + time_elapsed + type_id + shot_type + season_type + (1|team_id) + (1|team_id:season), data = df_shots_select, family = binomial(link = "logit"))
# 
# m_red <- glmer(scoring_play ~ shot_dist + time_elapsed + type_id + shot_type + season_type + (1|team_id), data = df_shots_select, family = binomial(link = "logit"))
# 
# m_rnd <- glmer(scoring_play ~ shot_dist + time_elapsed + season_type + shot_type + (1 | team_id) + (1 | athlete_id_1) + (1 | season:team_id), data = df_shots_select, family = binomial(link = "logit"))

# FINAL MODEL
# fixed effects for team and season
# random effect for player
m_rnd2 <- glmer(scoring_play ~ shot_dist + time_elapsed + season_type + shot_type + team_id*season + (1 | athlete_id_1), data = df_shots_select, family = binomial(link = "logit"))

summary(m_full)
summary(m_red)
AIC(m_full)
AIC(m_red)
summary(m_rnd)
AIC(m_rnd)
summary(m_rnd2)
AIC(m_rnd2)
vif(m_rnd2)


tidy(m_rnd2) |>
  write.csv("glm_modelterms.csv")

preds <- predict(m_rnd2, newdata = df_shots_select, type = "response")
as.tibble(preds)

glm_shots_predicted2 <- df_shots_select |>
  cbind(preds) |>
  relocate(preds, scoring_play) |>
  mutate(
    miss_group = cumsum(lag(scoring_play, default = 0) == 0),  # resets after a miss
    streak = ave(scoring_play, miss_group, FUN = cumsum),      # running makes within streak
    after_3_makes = ifelse(lag(streak, default = 0) >= 3, 1, 0),
    
    make_group = cumsum(lag(scoring_play, default = 0) == 1),
    miss_streak = ave(1 - scoring_play, make_group, FUN = cumsum),
    after_3_misses = ifelse(lag(miss_streak, default = 0) >= 3, 1, 0),
    
    sequence_type = case_when(after_3_misses == 1 ~ 0,
                              after_3_makes == 1 ~ 1,
                              after_3_makes == 0 & after_3_misses == 0 ~ 2),
    streak_group = if_else(streak >= 3, "3+", "0-2"),
    streak_group = factor(streak_group, levels = c("0-2", "3+")),
    streak_group_2 = case_when(streak == 0 ~ "0",
                               streak == 1 ~ "1",
                               streak == 2 ~ "2",
                               streak == 3 ~ "3",
                               streak >= 4 ~ "4+"),
    streak_before = streak - scoring_play,
    streak_before = case_when(streak_before == 0 ~ "0",
                               streak_before == 1 ~ "1",
                               streak_before == 2 ~ "2",
                               streak_before >= 3 ~ "3+"),
    miss_streak_before = miss_streak - (1 - scoring_play),
miss_streak_before = case_when(
  miss_streak_before == 0 ~ "0",
  miss_streak_before == 1 ~ "1",
  miss_streak_before == 2 ~ "2",
  miss_streak_before >= 3 ~ "3+"
)
  ) |>
  ungroup()
```


```{r}
set.seed(619)
n_sims = 10000

sim_results_2022 <- glm_shots_predicted2 |>
  filter(team_id == 17,
         season == 2022) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  summarize(
    observed_stat = phat_Sstreak_Fstreak(scoring_play, 3),
    
    sim_stats = list(
      replicate(
        n_sims,
        phat_Sstreak_Fstreak(
          rbinom(n = n(), size = 1, prob = preds),
          3
        )
      )
    ),
    .groups = "drop"
  ) |>
  unnest_wider(sim_stats, names_sep = "_") |>
  rename_with(
    ~ paste0("sim_", seq_along(.)),
    starts_with("sim_stats_")
  ) |>
  rowwise() |>
  mutate(
    p_value = mean(c_across(starts_with("sim_")) >= observed_stat, na.rm = TRUE),
    mean = mean(c_across(starts_with("sim_")), na.rm = T),
    sd = sd(c_across(starts_with("sim_")), na.rm = T)
  ) |>
  ungroup()

# results of simulations
sim_results_2022 |>
  select(-c(3:10002)) |>
  arrange(p_value)

p.adjust(sim_results_2022$p_value, method = "BY") |>
  cbind(sim_results_2022) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(season == 2022, team_id == 17) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |> dplyr::select(season, team_id, game_id, miss_streaks, make_streaks), by = join_by("game_id" == "game_id")) |>
  write_csv("2022_pvalues.csv")

# let's look at games that have low p-values
df_shots |>
  filter(team_id == 17,
         season == 2022,
         game_id %in% c(401391727, 
                        401391828, 
                        401391678,
                        401455683)) |>
  group_by(game_id) |>
  arrange(game_id, time_elapsed) |>
  summarize(statistics = streak_stats(scoring_play, 3)) |>
  unnest_wider(statistics)

longer_2022 <- sim_results_2022 |>
  pivot_longer(
    cols = starts_with("sim_"),
    names_to = "simulation",
    values_to = "sim_value"
  )

sample_games <- sim_results_2022 |> 
  slice_min(p_value, n = 6) |>
  pull(game_id)
  

longer_2022 |> filter(game_id %in% sample_games) |>
  mutate(game_id = as_factor(game_id),
         game_id = game_id |> recode_values(
                "401391727" ~ "vs. LA Sparks",
                "401391828" ~ "vs. IN Fever",
                "401391678" ~ "vs. MN Lynx",
                "401455683" ~ "vs. CT Sun",
                "401391747" ~ "vs. CHI Sky",
                "401391782" ~ "vs. NY Liberty")) |>
  
  ggplot(aes(x = sim_value)) +
  geom_histogram(bins = 40) +
  geom_vline(
    aes(xintercept = observed_stat),
    color = "red"
  ) +
  facet_wrap(~ game_id, scales = "free") + labs(title = "Greatest Streak Statistics for 2022 LV Aces",
  subtitle = "On simulated null distributions",
   x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
  y = "Frequency") + theme_minimal() + theme(panel.grid.minor = element_blank())

longer_2022 |>
  filter(game_id == 401391727) |>
  ggplot(aes(x = sim_value)) + 
  geom_histogram(aes(fill = after_stat(x >= 0.5)), bins = 40) + scale_fill_manual(
    values = c("FALSE" = "gray40", "TRUE" = "red"),
    guide = "none"   # removes legend
  ) +
  geom_vline(
    aes(xintercept = observed_stat),
    color = "red"
  ) + geom_vline(aes(xintercept = mean), color = "blue", lty = 2) + labs(title = "Streak Statistic for 2022 LV Aces vs. LA Sparks on 6/11/22",
  subtitle = "Over simulated null distribution",
   x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
  y = "Frequency") + theme_minimal() + theme(panel.grid.minor = element_blank()) + annotate("text", x = .3, y = 800, label = "p-value = 0.003") + annotate("text", x = -.4, y = 800, label = "Sample Mean = -0.14")
```

```{r}
set.seed(619)
sim_results_2023 <- glm_shots_predicted2 |>
  filter(team_id == 17,
         season == 2023) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  summarize(
    observed_stat = phat_Sstreak_Fstreak(scoring_play, 3),
    
    sim_stats = list(
      replicate(
        n_sims,
        phat_Sstreak_Fstreak(
          rbinom(n = n(), size = 1, prob = preds),
          3
        )
      )
    ),
    .groups = "drop"
  ) |>
  unnest_wider(sim_stats, names_sep = "_") |>
  rename_with(
    ~ paste0("sim_", seq_along(.)),
    starts_with("sim_stats_")
  ) |>
  rowwise() |>
  mutate(
    p_value = mean(c_across(starts_with("sim_")) >= observed_stat, na.rm = TRUE),
    mean = mean(c_across(starts_with("sim_")), na.rm = T),
    sd = sd(c_across(starts_with("sim_")), na.rm = T)
  ) |>
  ungroup()

sim_results_2023 |>
  select(-c(3:10002)) |>
  arrange(p_value)

sim_results_2023 |> pull(p_value) |>
  na.omit() |>
  p.adjust(method = "BY") |>
  cbind(sim_results_2023 |> filter(!is.na(p_value))) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(season == 2023, team_id == 17) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |> dplyr::select(season, team_id, game_id, miss_streaks, make_streaks), by = join_by("game_id" == "game_id")) |>
  write_csv("2023_pvalues.csv")


df_shots |>
  filter(team_id == 17,
         season == 2023,
         game_id %in% c(401507310, 
                        401578554)) |>
  group_by(game_id) |>
  arrange(game_id, time_elapsed) |>
  summarize(statistics = streak_stats(scoring_play, 3)) |>
  unnest_wider(statistics)



longer_2023 <- sim_results_2023 |>
  pivot_longer(
    cols = starts_with("sim_"),
    names_to = "simulation",
    values_to = "sim_value"
  )

sample_games <- sim_results_2023 |> 
  slice_min(p_value, n = 6) |>
  pull(game_id)

longer_2023 |>
  filter(game_id %in% sample_games) |>
  mutate(game_id = as_factor(game_id),
         game_id = game_id |> recode_values(
                "401507310" ~ "vs. ATL Dream",
                "401578554" ~ "vs. CHI Sky",
                "401578574" ~ "vs. NY Liberty 1",
                "401507292" ~ "vs. NY Liberty 2",
                "401507248" ~ "vs. LA Sparks",
                "401507322" ~ "vs. ATL Dream 2")
               ) |>
ggplot(aes(x = sim_value)) +
  geom_histogram(bins = 40) +
  geom_vline(aes(xintercept = observed_stat),
    color = "red"
  ) +
  facet_wrap(~ game_id, scales = "free") + labs(title = "Greatest Streak Statistics for 2023 LV Aces",
                                                subtitle = "On simulated null distributions",
                                                x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
                                                y = "Frequency") + theme_minimal() + theme(panel.grid.minor = element_blank())

```


```{r}
set.seed(619)
sim_results_2024 <- glm_shots_predicted2 |>
  filter(team_id == 9,
         season == 2024) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  summarize(
    observed_stat = phat_Sstreak_Fstreak(scoring_play, 3),
    
    sim_stats = list(
      replicate(
        n_sims,
        phat_Sstreak_Fstreak(
          rbinom(n = n(), size = 1, prob = preds),
          3
        )
      )
    ),
    .groups = "drop"
  ) |>
  unnest_wider(sim_stats, names_sep = "_") |>
  rename_with(
    ~ paste0("sim_", seq_along(.)),
    starts_with("sim_stats_")
  ) |>
  rowwise() |>
  mutate(
    p_value = mean(c_across(starts_with("sim_")) >= observed_stat, na.rm = TRUE),
    mean = mean(c_across(starts_with("sim_")), na.rm = T),
    sd = sd(c_across(starts_with("sim_")), na.rm = T)
  ) |>
  ungroup()

sim_results_2024 |>
  select(-c(3:10002)) |>
  arrange(p_value)

p.adjust(sim_results_2024$p_value, method = "BY") |>
  cbind(sim_results_2024) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(season == 2024, team_id == 9) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |> dplyr::select(season, team_id, game_id, miss_streaks, make_streaks), by = join_by("game_id" == "game_id")) |>
  write_csv("2024_pvalues.csv")

df_shots |>
  filter(team_id == 9,
         season == 2024,
         game_id %in% c(401620311, 
                        401677672)) |>
  group_by(game_id) |>
  arrange(game_id, time_elapsed) |>
  summarize(statistics = streak_stats(scoring_play, 3)) |>
  unnest_wider(statistics)

longer_2024 <- sim_results_2024 |>
  pivot_longer(
    cols = starts_with("sim_"),
    names_to = "simulation",
    values_to = "sim_value"
  )

sample_games <- sim_results_2024 |> 
  slice_min(p_value, n = 6) |>
  pull(game_id)

longer_2024 |>
  filter(game_id %in% sample_games) |>
  mutate(game_id = as_factor(game_id),
         game_id = game_id |> recode_values(
                "401620311" ~ "vs. ATL Dream 1",
                "401677672" ~ "vs. MN Lynx",
                "401620252" ~ "vs. PHX Mercury",
                "401721255" ~ "vs. ATL Dream 2",
                "401620309" ~ "vs. LA Sparks",
                "401620263" ~ "vs. IN Fever")
               ) |>
ggplot(aes(x = sim_value)) +
  geom_histogram(bins = 40) +
  geom_vline(
    aes(xintercept = observed_stat),
    color = "red"
  ) +
  facet_wrap(~ game_id, scales = "free") + labs(title = "Greatest Streak Statistics for 2024 NY Liberty",
                                                subtitle = "On simulated null distributions",
                                                x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
                                                y = "Frequency") + theme_minimal() + theme(panel.grid.minor = element_blank())
```

What happened during these games?
```{r}
df_shots |>
  filter(team_id == 9,
         season == 2024,
         game_id %in% c(401620311, 
                        401677672))
```

# Summarize How Often Streaks Occur

```{r}
glm_shots |>
  group_by(season) |>
  summarize(n_games = n_distinct(game_id),
            num_streaks_3plus = sum(streak_before == "3+"),
            avg_nstreaks = num_streaks_3plus/n_games) |>
  write_csv("avg_nstreaks.csv")

glm_shots |>
  group_by(season) |>
  summarize(n_games = n_distinct(game_id),
            num_missstreaks_3plus = sum(miss_streak_before == "3+"),
            avg_nmissstreaks = num_missstreaks_3plus/n_games) |>
  write_csv("avg_nmissstreaks.csv")

glm_shots |>
  mutate(streak_before = streak - scoring_play,
         miss_streak_before = miss_streak - (1 - scoring_play)) |>
  group_by(season) |>
  filter(streak_before >= 3) |>
  summarize(mean_streak = mean(streak_before)) |>
  write_csv("mean_streaklength.csv")
  
  
glm_shots |>
  mutate(streak_before = streak - scoring_play,
         miss_streak_before = miss_streak - (1 - scoring_play)) |>
  group_by(season) |>
  filter(miss_streak_before >= 3) |>
  summarize(mean_missstreak = mean(miss_streak_before)) |>
  write_csv("mean_missstreaklength.csv")

glm_shots |>
  group_by(season, team_id, game_id) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
  write_csv("n_streakspergame.csv")

df_shots |> filter(game_id == 401391655, team_id == 3)

```

## Join number of streaks with p-values

```{r}
p.adjust(sim_results_2022$p_value, method = "BY") |>
  cbind(sim_results_2022) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2022) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2022_pvalues.csv")

p.adjust(sim_results_2023$p_value, method = "BY") |>
  cbind(sim_results_2023) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2023) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2023_pvalues.csv")


p.adjust(sim_results_2024$p_value, method = "BY") |>
  cbind(sim_results_2024) |>
  select(-c(4:10003)) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 9, season == 2024) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id")) |>
  write_csv("2024_pvalues.csv")
# |>
#   write_csv("2022_pvalues.csv")
```


## Summary of main streak statistic

```{r}
df_shots |>
  group_by(season, team_id, game_id) |>
  summarize(streak_stats = phat_Sstreak_Fstreak(scoring_play, 3)) |>
  ggplot(aes(x = streak_stats)) + geom_histogram(bins = 40) + theme_minimal()  + geom_vline(aes(xintercept = mean(streak_stats, na.rm = T), color = "red")) +  theme(panel.grid.minor = element_blank(),
                                                                                                                                                          legend.position = "none") + labs(x = expression("P(hit | 3 hits) = P(hit | 3 misses)"),
                                                                                                                      y = "Density",
                                                                                                                      title = "Streak Statistic Distribution Across the League",
                                                                                                                      subtitle = "Mean = -0.143, SD = 0.287")

df_shots |>
  mutate(group = case_when(
    team_id == 17 & season == 2022 ~ "LV Aces 2022",
    team_id == 17 & season == 2023 ~ "LV Aces 2023",
    team_id == 9 & season == 2024 ~ "NY Liberty 2024",
    TRUE ~ "Rest of League"
  )) |>
  group_by(group, game_id) |>
  summarize(streak_stats = phat_Sstreak_Fstreak(scoring_play, 3)) |>
    ggplot(aes(x = streak_stats)) + geom_density() + theme_minimal() + facet_wrap(~group)

df_shots |>
  mutate(group = case_when(
    team_id == 17 & season == 2022 ~ "LV Aces 2022",
    team_id == 17 & season == 2023 ~ "LV Aces 2023",
    team_id == 9 & season == 2024 ~ "NY Liberty 2024",
    TRUE ~ "Rest of League"
  )) |>
  group_by(group, game_id) |>
  summarize(streak_stats = phat_Sstreak_Fstreak(scoring_play, 3)) |>
  ungroup() |>
  group_by(group) |>
  summarize(mean_diff = mean(streak_stats, na.rm = T),
            sd_diff = sd(streak_stats, na.rm = T))



df_shots |>
  group_by(season, team_id, game_id) |>
  summarize(streak_stats = phat_Sstreak_Fstreak(scoring_play, 3)) |>
  ungroup() |>
  summarize(mean = mean(streak_stats, na.rm = T),
            sd = sd(streak_stats, na.rm = T))
```

## Non-bias adjusted t-tests

```{r}
# 2022
unadj_2022 <- glm_shots |>
  mutate(group = case_when(
  streak_before == "3+" ~ "make_streak",
  miss_streak_before == "3+" ~ "miss_streak"
)) |>
  filter(team_id == 17,
         season == 2022,
         !is.na(group)) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  filter(
    sum(group == "make_streak") >= 2,
    sum(group == "miss_streak") >= 2,
    var(scoring_play[group == "make_streak"]) > 0,
    var(scoring_play[group == "miss_streak"]) > 0
  ) |>
  summarize(p_value = t.test(scoring_play ~ group, alternative = "greater")$p.value,
  diff = mean(scoring_play[group == "make_streak"]) -
         mean(scoring_play[group == "miss_streak"])) |>
  arrange(p_value) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2022) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id"))

# 2023
unadj_2023 <- glm_shots |>
  mutate(group = case_when(
  streak_before == "3+" ~ "make_streak",
  miss_streak_before == "3+" ~ "miss_streak"
)) |>
  filter(team_id == 17,
         season == 2023,
         !is.na(group)) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  filter(
    sum(group == "make_streak") >= 2,
    sum(group == "miss_streak") >= 2,
    var(scoring_play[group == "make_streak"]) > 0,
    var(scoring_play[group == "miss_streak"]) > 0
  ) |>
  summarize(p_value = t.test(scoring_play ~ group, alternative = "greater")$p.value,
  diff = mean(scoring_play[group == "make_streak"]) -
         mean(scoring_play[group == "miss_streak"])) |>
  arrange(p_value) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 17, season == 2023) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id"))

# 2024
unadj_2024 <- glm_shots |>
  mutate(group = case_when(
  streak_before == "3+" ~ "make_streak",
  miss_streak_before == "3+" ~ "miss_streak"
)) |>
  filter(team_id == 9,
         season == 2024,
         !is.na(group)) |>
  arrange(game_id, time_elapsed) |>
  group_by(game_id) |>
  filter(
    sum(group == "make_streak") >= 2,
    sum(group == "miss_streak") >= 2,
    var(scoring_play[group == "make_streak"]) > 0,
    var(scoring_play[group == "miss_streak"]) > 0
  ) |>
  summarize(p_value = t.test(scoring_play ~ group, alternative = "greater")$p.value,
  diff = mean(scoring_play[group == "make_streak"]) -
         mean(scoring_play[group == "miss_streak"])) |>
  arrange(p_value) |>
  left_join(glm_shots |>
  group_by(season, team_id, game_id) |>
    filter(team_id == 9, season == 2024) |>
  summarize(miss_streaks = sum(as.numeric(miss_streak_before == "3+")),
            make_streaks = sum(as.numeric(streak_before == "3+")),
            fga = sum(shooting_play),
            fgm = sum(scoring_play)) |>
  ungroup() |>
    dplyr::select(game_id, miss_streaks, make_streaks),
  by = join_by("game_id" == "game_id"))
```

## Join dataframes

```{r}
pvalues_2022 <- read_csv("2022_pvalues.csv")
pvalues_2023 <- read_csv("2023_pvalues.csv")
pvalues_2024 <- read_csv("2024_pvalues.csv")

perm2022 <- read_csv("2022_permutations.csv") |>
  mutate(p_valueperm = p_value) |>
  dplyr::select(-p_value)
perm2023 <- read_csv("2023_permutations.csv") |>
  mutate(p_valueperm = p_value) |>
  dplyr::select(-p_value)
perm2024 <- read_csv("2024_permutations.csv") |>
  mutate(p_valueperm = p_value) |>
  dplyr::select(-p_value)

# "observed stat" from simulations
# "observed" from permutations
# "diff" from unadjusted t-tests

pvalues_2022 |>
  left_join(unadj_2022, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2022, by = c("game_id")) |>
  write_csv("joinedpvalues2022.csv")



pvalues_2022 |>
  left_join(unadj_2022, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2022, by = "game_id") |>
  ggplot(aes(x = p_valuesim, y = p_valueperm)) + geom_point() + geom_abline(slope = 1, intercept = 0)

pvalues_2023 |>
  left_join(unadj_2023, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2023, by = c("game_id")) |>
  write_csv("joinedpvalues2023.csv")

pvalues_2023 |>
  left_join(unadj_2023, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2023, by = "game_id") |>
  ggplot(aes(x = p_valuesim, y = p_valueperm)) + geom_point() + geom_abline(slope = 1, intercept = 0)

pvalues_2024 |>
  left_join(unadj_2024, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2024, by = c("game_id")) |>
  write_csv("joinedpvalues2024.csv")

pvalues_2024 |>
  left_join(unadj_2024, by = "game_id",
            suffix = c("sim", "unadj")) |>
  left_join(perm2024, by = "game_id") |>
  ggplot(aes(x = p_valuesim, y = p_valueperm)) + geom_point() + geom_abline(slope = 1, intercept = 0)
```

## Make visualizations based on comparing distributions



